# Generated by Django 4.0.4 on 2022-05-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=400, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
