# Generated by Django 4.0.4 on 2022-05-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_blog_short_description_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
