# Generated by Django 4.0.4 on 2022-05-05 02:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0014_star'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Star',
            new_name='Review',
        ),
    ]
