# Generated by Django 4.0.4 on 2022-05-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_star_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='first_time',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
