# Generated by Django 4.0.4 on 2022-05-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='aaaaaa',
            field=models.IntegerField(default=0),
        ),
    ]
