# Generated by Django 4.0.4 on 2022-05-05 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_review_aaaaaa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='aaaaaa',
            new_name='b',
        ),
    ]
