# Generated by Django 4.0.4 on 2022-05-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_review_b_alter_blog_comment_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unsale_price',
            field=models.IntegerField(null=True),
        ),
    ]
