# Generated by Django 4.0.4 on 2022-05-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
