# Generated by Django 4.0.4 on 2022-05-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_address_time_alter_blog_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
